version: '3.1'

services:
    db:
        container_name: db
        image: postgres:13
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: experiencedb
    #adminer:
    #    image: adminer
    #    restart: always
    #    ports:
    #        - 8081:8080
    app:
        build: .
        container_name: app
        ports:
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/experiencedb
